(function () {

    function getReportData() {
        const tasks = appState.tasks || [];

        const completed =
            tasks.filter(task => task.completed);

        const pending =
            tasks.filter(task => !task.completed);

        const totalStudySeconds =
            tasks.reduce(
                (total, task) =>
                    total +
                    (Number(task.actualStudyTime) || 0),
                0
            );

        const totalXP =
            Number(appState.xp) || 0;

        const level =
            Number(appState.level) || 1;

        return {
            totalTasks: tasks.length,
            completedTasks: completed.length,
            pendingTasks: pending.length,
            totalStudyMinutes:
                Math.round(totalStudySeconds / 60),
            totalXP,
            level
        };
    }

    function downloadReport() {

        const data =
            getReportData();

        const completionRate =
            data.totalTasks > 0
                ? Math.round(
                    (data.completedTasks /
                        data.totalTasks) * 100
                )
                : 0;

        const date =
            new Date().toLocaleDateString();

        const report = `
STUDYQUEST — PRODUCTIVITY REPORT
================================

Generated: ${date}

OVERVIEW
--------
Level: ${data.level}
XP: ${data.totalXP}

Total Tasks: ${data.totalTasks}
Completed Tasks: ${data.completedTasks}
Pending Tasks: ${data.pendingTasks}

Completion Rate: ${completionRate}%

TOTAL STUDY TIME
----------------
${data.totalStudyMinutes} minutes

TASK SUMMARY
------------

Completed:
${data.completedTasks}

Pending:
${data.pendingTasks}

PRODUCTIVITY
------------

Completion Rate:
${completionRate}%

Keep studying consistently and build your learning streak!

================================
Generated by StudyQuest
`;

        const blob =
            new Blob(
                [report],
                {
                    type: "text/plain;charset=utf-8"
                }
            );

        const url =
            URL.createObjectURL(blob);

        const link =
            document.createElement("a");

        link.href = url;

        link.download =
            `StudyQuest-Report-${new Date()
                .toISOString()
                .split("T")[0]}.txt`;

        document.body.appendChild(link);

        link.click();

        document.body.removeChild(link);

        URL.revokeObjectURL(url);
    }

    function renderReportButton() {

        const analyticsSection =
            document.getElementById(
                "analytics-section"
            );

        if (!analyticsSection) return;

        if (
            document.getElementById(
                "report-container"
            )
        ) return;

        const container =
            document.createElement("div");

        container.id =
            "report-container";

        container.className =
            "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-8";

        container.innerHTML = `
            <div class="glass-card rounded-2xl p-6 shadow-lg border border-gray-200 dark:border-gray-700">

                <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">

                    <div class="flex items-center gap-3">

                        <div class="w-11 h-11 rounded-xl bg-indigo-100 dark:bg-indigo-900 flex items-center justify-center">

                            <i class="fas fa-file-download text-indigo-600 dark:text-indigo-300"></i>

                        </div>

                        <div>

                            <h2 class="text-xl font-bold text-gray-800 dark:text-white">
                                Export Your Progress
                            </h2>

                            <p class="text-sm text-gray-500 dark:text-gray-400">
                                Save a summary of your StudyQuest progress.
                            </p>

                        </div>

                    </div>

                    <button
                        id="download-study-report"
                        class="px-5 py-3 rounded-xl bg-indigo-600 text-white font-semibold hover:bg-indigo-700 transition"
                    >
                        <i class="fas fa-download mr-2"></i>
                        Download Report
                    </button>

                </div>

            </div>
        `;

        analyticsSection.appendChild(
            container
        );

        document
            .getElementById(
                "download-study-report"
            )
            .addEventListener(
                "click",
                downloadReport
            );
    }

    window.downloadStudyReport =
        downloadReport;

    document.addEventListener(
        "DOMContentLoaded",
        function () {

            setTimeout(
                renderReportButton,
                900
            );

        }
    );

})();